//! HCI constants: packet type indicators, op codes, event/subevent codes, and
//! status. Values ported verbatim from `bumble.hci`.

// Packet type indicators (the first byte of every HCI packet).
pub const HCI_COMMAND_PACKET: u8 = 0x01;
pub const HCI_ACL_DATA_PACKET: u8 = 0x02;
pub const HCI_SYNCHRONOUS_DATA_PACKET: u8 = 0x03;
pub const HCI_EVENT_PACKET: u8 = 0x04;
pub const HCI_ISO_DATA_PACKET: u8 = 0x05;

// Command op codes (OGF << 10 | OCF).
pub const HCI_DISCONNECT_COMMAND: u16 = 0x0406;
pub const HCI_PIN_CODE_REQUEST_REPLY_COMMAND: u16 = 0x040D;
pub const HCI_SET_EVENT_MASK_COMMAND: u16 = 0x0C01;
pub const HCI_RESET_COMMAND: u16 = 0x0C03;
pub const HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND: u16 = 0x1001;
pub const HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND: u16 = 0x1002;
pub const HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND: u16 = 0x1003;
pub const HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND: u16 = 0x100B;
pub const HCI_READ_LOCAL_SUPPORTED_CODECS_V2_COMMAND: u16 = 0x100D;
pub const HCI_READ_BD_ADDR_COMMAND: u16 = 0x1009;
pub const HCI_READ_LOCAL_NAME_COMMAND: u16 = 0x0C14;
pub const HCI_LE_READ_BUFFER_SIZE_COMMAND: u16 = 0x2002;
pub const HCI_LE_SET_EVENT_MASK_COMMAND: u16 = 0x2001;
pub const HCI_LE_SET_RANDOM_ADDRESS_COMMAND: u16 = 0x2005;
pub const HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND: u16 = 0x2006;
pub const HCI_LE_SET_ADVERTISING_DATA_COMMAND: u16 = 0x2008;
pub const HCI_LE_SET_ADVERTISING_ENABLE_COMMAND: u16 = 0x200A;
pub const HCI_LE_SET_SCAN_PARAMETERS_COMMAND: u16 = 0x200B;
pub const HCI_LE_SET_SCAN_ENABLE_COMMAND: u16 = 0x200C;
pub const HCI_LE_CREATE_CONNECTION_COMMAND: u16 = 0x200D;
pub const HCI_LE_ADD_DEVICE_TO_FILTER_ACCEPT_LIST_COMMAND: u16 = 0x2011;
pub const HCI_LE_REMOVE_DEVICE_FROM_FILTER_ACCEPT_LIST_COMMAND: u16 = 0x2012;
pub const HCI_LE_CONNECTION_UPDATE_COMMAND: u16 = 0x2013;
pub const HCI_LE_READ_REMOTE_FEATURES_COMMAND: u16 = 0x2016;
pub const HCI_LE_SET_DEFAULT_PHY_COMMAND: u16 = 0x2031;
pub const HCI_LE_SET_EXTENDED_ADVERTISING_ENABLE_COMMAND: u16 = 0x2039;
pub const HCI_LE_SET_EXTENDED_SCAN_PARAMETERS_COMMAND: u16 = 0x2041;
pub const HCI_LE_EXTENDED_CREATE_CONNECTION_COMMAND: u16 = 0x2043;
pub const HCI_LE_SETUP_ISO_DATA_PATH_COMMAND: u16 = 0x206E;

// Event codes.
pub const HCI_DISCONNECTION_COMPLETE_EVENT: u8 = 0x05;
pub const HCI_COMMAND_COMPLETE_EVENT: u8 = 0x0E;
pub const HCI_COMMAND_STATUS_EVENT: u8 = 0x0F;
pub const HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT: u8 = 0x13;
pub const HCI_LE_META_EVENT: u8 = 0x3E;

// LE Meta sub-event codes.
pub const HCI_LE_CONNECTION_COMPLETE_EVENT: u8 = 0x01;
pub const HCI_LE_ADVERTISING_REPORT_EVENT: u8 = 0x02;
pub const HCI_LE_CONNECTION_UPDATE_COMPLETE_EVENT: u8 = 0x03;
pub const HCI_LE_READ_REMOTE_FEATURES_COMPLETE_EVENT: u8 = 0x04;
pub const HCI_LE_EXTENDED_ADVERTISING_REPORT_EVENT: u8 = 0x0D;
pub const HCI_LE_CHANNEL_SELECTION_ALGORITHM_EVENT: u8 = 0x14;

// Status.
pub const HCI_SUCCESS: u8 = 0x00;

/// Decompose an op code into (OGF, OCF).
pub fn ogf_ocf(op_code: u16) -> (u8, u16) {
    ((op_code >> 10) as u8, op_code & 0x03FF)
}

/// Compose an op code from OGF and OCF.
pub fn op_code(ogf: u8, ocf: u16) -> u16 {
    ((ogf as u16) << 10) | (ocf & 0x03FF)
}
