#!/usr/bin/env python3
"""Generate symbolic HCI metadata tables from upstream ``bumble.hci``.

Unlike the packet generators, this script parses the source text and therefore
does not need Bumble's Python dependencies installed. Set ``BUMBLE_SRC`` to an
upstream checkout; it defaults to ``/tmp/bumble-scope``.
"""

import os
import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = pathlib.Path(os.environ.get("BUMBLE_SRC", "/tmp/bumble-scope")) / "bumble/hci.py"
DESTINATION = ROOT / "src/metadata_tables.rs"


def class_body(source: str, class_name: str) -> str:
    match = re.search(
        rf"^class {re.escape(class_name)}\([^\n]*\):\n(?P<body>.*?)(?=^class |^# -{{10,}})",
        source,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise SystemExit(f"could not find class {class_name}")
    return match.group("body")


def enum_values(source: str, class_name: str) -> list[tuple[int, str]]:
    values = []
    for name, value in re.findall(
        r"^\s{4}([A-Z][A-Z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*$",
        class_body(source, class_name),
        re.MULTILINE,
    ):
        values.append((int(value, 0), name))
    if not values:
        raise SystemExit(f"could not parse values for {class_name}")
    return values


def supported_commands(source: str) -> list[tuple[int, int, str]]:
    match = re.search(
        r"^HCI_SUPPORTED_COMMANDS_MASKS = \{\n(?P<body>.*?)^\}\n",
        source,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise SystemExit("could not find HCI_SUPPORTED_COMMANDS_MASKS")
    commands = []
    pattern = re.compile(
        r"^\s*(HCI_[A-Z0-9_]+_COMMAND)\s*:\s*1\s*<<\s*\((\d+)\*8\+(\d+)\),?\s*$",
        re.MULTILINE,
    )
    for name, byte_index, bit_index in pattern.findall(match.group("body")):
        commands.append((int(byte_index), 1 << int(bit_index), name))
    if len(commands) < 300:
        raise SystemExit(f"parsed only {len(commands)} supported commands")
    return commands


def rust_table(name: str, rust_type: str, values: list[tuple]) -> list[str]:
    lines = [f"pub(crate) const {name}: &[{rust_type}] = &["]
    for value in values:
        rendered = ", ".join(f'"{item}"' if isinstance(item, str) else str(item) for item in value)
        lines.append(f"    ({rendered}),")
    lines.append("];")
    return lines


def main() -> None:
    source = SOURCE.read_text()
    lines = [
        "// GENERATED by `tools/hcigen/gen_metadata.py` from upstream `bumble.hci`.",
        "// Do not edit by hand.",
        "",
    ]
    lines += rust_table(
        "SPECIFICATION_VERSION_NAMES",
        "(u8, &str)",
        enum_values(source, "SpecificationVersion"),
    )
    lines.append("")
    lines += rust_table(
        "LE_FEATURE_NAMES", "(u8, &str)", enum_values(source, "LeFeature")
    )
    lines.append("")
    lines += rust_table(
        "CODEC_ID_NAMES", "(u8, &str)", enum_values(source, "CodecID")
    )
    lines.append("")
    lines += rust_table(
        "SUPPORTED_COMMAND_NAMES",
        "(usize, u8, &str)",
        supported_commands(source),
    )
    lines.append("")
    DESTINATION.write_text("\n".join(lines))
    print(f"wrote {DESTINATION}")


if __name__ == "__main__":
    main()
